### ISSUE TITLE
Runtime Failure on awscli 1.13+

### ISSUE THREAD

**Issue by hikerspath** [paperg/awsudo#7] opened 2017-12-08 14:58 UTC
getting the following error when attempting to run awsudo on newer versions of awscli python libraries.

Latest working version:
```
awscli-1.12.2
botocore-1.8.2
```

Failures start in following:
```
awscli-1.13.0
botocore-1.8.3
```

Specific message / issue:
```
# awsudo -u profile_name env
Traceback (most recent call last):
  File "/root/.local/bin/awsudo", line 9, in <module>
    load_entry_point('awsudo==0.0.0', 'console_scripts', 'awsudo')()
  File "/root/.local/lib/python2.7/site-packages/awsudo/main.py", line 68, in main
    run(args, resolver.getEnvironment(profile))
  File "/root/.local/lib/python2.7/site-packages/awsudo/config.py", line 16, in getEnvironment
    session.emit('session-initialized', session=session)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 719, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
TypeError: attach_history_handler() takes exactly 2 arguments (1 given)
```

The 'attach_history_handler()' exists in the new history options of the aws-cli that started in that version.
- https://github.com/aws/aws-cli/pull/2993

**Comment by ktilcu** [comment] 2017-12-19 16:09
@hikerspath Thanks for pointing this out. Feel free to take a stab at this. Otherwise we will likely take a little bit to circle around.

**Comment by ktilcu** [comment] 2017-12-19 16:43
A quick peek makes me think that it's a problem in botocore. I can dig  more later.

**Comment by yanotoma** [comment] 2018-01-07 12:55
Hi! I have the same problem, do you have any update about this? thanks!

**Comment by ktilcu** [comment] 2018-02-06 22:02
@yanotoma @hikerspath We have a temporary fix in. Let me know if you have any problems with it.

**Comment by rizkidoank** [comment] 2018-03-14 11:47
Hello @ktilcu ,
I'm trying to fix this issue in PR https://github.com/makethunder/awsudo/pull/10 .
apparently it's caused by 'session-initialized' event being registered to attach_handler_history. In that PR, I register 'session-initialized' event to inject_assume_role_provider_cache.

Is there any reason to use awscli as dependency? If I looked into the code, probably we can remove the dependency of awscli to use only botocore as dependency to get cached credentials. CMIIW

**Comment by ktilcu** [comment] 2018-07-04 18:45
@yanotoma @hikerspath Sorry for the huge delay. I finally merged @rizkidoank's pull request. I think this should patch things up for the near term.

**Closed as completed by ktilcu** 2018-07-04 18:45 UTC
